version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
          - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 8000:80
            
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysql12345
            MYSQL_DATABASE: inject_demodb
            MYSQL_USER: trannguyenhan
            MYSQL_PASSWORD: mysql12345
        ports:
            - "9906:3306"
        volumes: 
            - ./sql/db.sql:/docker-entrypoint-initdb.d/dump.sql
